image: elixir:latest

cache:
  key: "$CI_JOB_NAME"
  paths:
    - deps
    - _build
    - /root/.mix

variables:
  MIX_ENV: "test"

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

test:
  script:
    - mix test

credo:
  script:
    - mix credo

audit:
  script:
    - mix hex.audit

format:
  script:
    - mix format --check-formatted

pages:
  stage: deploy
  script:
    - mix docs -o public
  artifacts:
    paths:
      - public
  only:
    - master

package:
  stage: deploy
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - mix hex.build
  artifacts:
    paths:
      - "angle-*.tar"
